In [1]:
import tensorflow as tf

In [2]:
arr = np.array([[1., 2., 3., 3.5],
                [4., 5., 6., 6.5],
                [7., 8., 9., 9.5]])

T1 = tf.constant(arr)
print(T1)

tf.Tensor(
[[1.  2.  3.  3.5]
 [4.  5.  6.  6.5]
 [7.  8.  9.  9.5]], shape=(3, 4), dtype=float64)


In [3]:
s = T1.get_shape()
print("T1의 크기:", s)
print("T1의 크기:", T1.shape)

T1의 크기: (3, 4)
T1의 크기: (3, 4)


In [4]:
T2 = tf.Variable(np.random.normal(size=s))
T3 = tf.Variable(np.random.normal(size=s[0]))

print(T2)
print(T3)

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float64, numpy=
array([[ 0.46967151, -0.28992556,  0.8726827 , -0.50303669],
       [ 1.31329992,  0.46022891,  0.2562046 , -0.15151519],
       [ 0.7351325 , -0.26638198, -0.40147826, -0.81129061]])>
<tf.Variable 'Variable:0' shape=(3,) dtype=float64, numpy=array([-2.97012408e+00,  4.22320537e-01,  2.47982105e-03])>


In [5]:
T4 = tf.reshape(T1, shape=[1, 1, -1])
T5 = tf.reshape(T1, shape=[1, 3, -1])

print(T4)
print(T5)

tf.Tensor([[[1.  2.  3.  3.5 4.  5.  6.  6.5 7.  8.  9.  9.5]]], shape=(1, 1, 12), dtype=float64)
tf.Tensor(
[[[1.  2.  3.  3.5]
  [4.  5.  6.  6.5]
  [7.  8.  9.  9.5]]], shape=(1, 3, 4), dtype=float64)


In [6]:
T6 = tf.transpose(T5, perm=[2, 1, 0])
T7 = tf.transpose(T5, perm=[0, 2, 1]) # shape=(1, 3, 4)

print(T6)
print(T7)

tf.Tensor(
[[[1. ]
  [4. ]
  [7. ]]

 [[2. ]
  [5. ]
  [8. ]]

 [[3. ]
  [6. ]
  [9. ]]

 [[3.5]
  [6.5]
  [9.5]]], shape=(4, 3, 1), dtype=float64)
tf.Tensor(
[[[1.  4.  7. ]
  [2.  5.  8. ]
  [3.  6.  9. ]
  [3.5 6.5 9.5]]], shape=(1, 4, 3), dtype=float64)


In [7]:
t5_splt = tf.split(T5,
                   num_or_size_splits=2,
                   axis=2)
print(t5_splt)

[<tf.Tensor: id=35, shape=(1, 3, 2), dtype=float64, numpy=
array([[[1., 2.],
        [4., 5.],
        [7., 8.]]])>, <tf.Tensor: id=36, shape=(1, 3, 2), dtype=float64, numpy=
array([[[3. , 3.5],
        [6. , 6.5],
        [9. , 9.5]]])>]


In [9]:
t1 = tf.ones(shape=(5, 1), dtype=tf.float32)
t2 = tf.zeros(shape=(5, 1), dtype=tf.float32)

print(t1)
print(t2)

tf.Tensor(
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]], shape=(5, 1), dtype=float32)
tf.Tensor(
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]], shape=(5, 1), dtype=float32)


In [10]:
t3 = tf.concat([t1, t2], axis=0)
t4 = tf.concat([t1, t2], axis=1)

print(t3)
print(t4)

tf.Tensor(
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]], shape=(10, 1), dtype=float32)
tf.Tensor(
[[1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]], shape=(5, 2), dtype=float32)
